import { describe, expect, test } from 'vitest';
import { GameReportSchema, type BookReport, type EngineEval } from '@freechesscoach/shared';
import { buildGameReport } from './build-game-report.js';
import { classifyMoves } from './classify.js';
import { parsePgn, type ParsedPosition } from './pgn.js';
import { tacticPreventionReason } from './tactic-reason-text.js';

// Generated by always playing chess.js's first-listed legal move from the
// start position — guaranteed legal by construction (no hand-transcription
// to get wrong), and deterministic, which the "byte-identical report" test
// below depends on.
const SAMPLE_PGN = `[White "Alice"]
[Black "Bob"]
[Result "1-0"]

1. a3 Nc6 2. a4 Rb8 3. a5 Ra8 4. a6 Rb8 5. axb7 Rxb7 6. b3 Nh6 7. b4 Rg8
8. b5 Rh8 9. b6 Rg8 10. bxa7 Rh8 11. a8=N Rg8 12. Nxc7+ Qxc7 13. c3 Kd8
14. c4 Ke8 15. c5 Kd8 16. d3 Ke8 17. d4 Kd8 18. d5 Ke8 19. d6 Kd8
20. dxc7+ Ke8 1-0`;

/** A flat, low-drama eval series (every move is "the engine's top choice at
 * a small, constant edge") — enough to exercise wiring without needing a
 * real engine, since this test is about assembly, not calibration. */
function buildEvals(positions: readonly ParsedPosition[]): EngineEval[] {
  return positions.map((position, index) => {
    const next = positions[index + 1];
    const lines = next?.moveSan
      ? [{ moveUci: next.moveUci ?? '', moveSan: next.moveSan, cp: 20, mateIn: null }]
      : [];
    return { ply: position.ply, fen: position.fen, depth: 16, lines };
  });
}

function buildFixtureBook(): BookReport {
  return {
    source: 'test-fixture@1',
    eco: 'C60',
    ecoVolume: 'C',
    name: 'Ruy Lopez',
    family: 'Ruy Lopez',
    variation: 'Closed',
    namedAtPly: 6,
    lastBookPly: 12,
    players: {
      white: { lastBookPly: 12, leftBookPly: 13, leftBookMove: 'Nf1', bookAlternatives: [] },
      black: { lastBookPly: 12, leftBookPly: 13, leftBookMove: 'Bf8', bookAlternatives: [] }
    }
  };
}

function buildFixtureReport() {
  const game = parsePgn(SAMPLE_PGN);
  const evals = buildEvals(game.positions);
  const moves = classifyMoves(game, evals, 'white');
  const book = buildFixtureBook();

  return buildGameReport({
    game,
    evals,
    moves,
    book,
    engine: { name: 'stockfish', depth: 16, multiPv: 1 },
    priorRating: { white: null, black: null },
    result: { white: 'win', black: 'loss' }
  });
}

describe('buildGameReport', () => {
  test('assembles a fully-populated, schema-valid report from a real game', () => {
    const report = buildFixtureReport();
    const parsed = GameReportSchema.safeParse(report);
    expect(parsed.success).toBe(true);
  });

  test('every move carries a resolved phase and tactical-position flag', () => {
    const report = buildFixtureReport();
    expect(report.moves.length).toBeGreaterThan(0);
    for (const move of report.moves) {
      expect(['opening', 'middlegame', 'endgame']).toContain(move.phase);
      expect(typeof move.isTacticalPosition).toBe('boolean');
    }
  });

  test('phase boundaries are monotone and never overlap', () => {
    const report = buildFixtureReport();
    const { openingEndPly, endgameStartPly } = report.phases;
    expect(openingEndPly).toBeGreaterThan(0);
    if (endgameStartPly !== null) expect(endgameStartPly).toBeGreaterThan(openingEndPly);
  });

  test("phase accuracies are merely present, not required to average to the game accuracy (§6.4)", () => {
    const report = buildFixtureReport();
    const { accuracy, phaseAccuracy } = report.players.white;
    const presentPhaseAccuracies = Object.values(phaseAccuracy).filter((value): value is number => value !== null);
    expect(presentPhaseAccuracies.length).toBeGreaterThan(0);
    // Deliberately not asserting equality to `accuracy` — a plain mean across
    // phases is not the same computation as the full-game weighted blend.
    expect(typeof accuracy).toBe('number');
  });

  test('per-colour classification counts sum to that colour\'s move count', () => {
    const report = buildFixtureReport();
    for (const colour of ['white', 'black'] as const) {
      const total = Object.values(report.players[colour].counts).reduce((sum, count) => sum + count, 0);
      const moveCount = report.moves.filter((move) => move.mover === colour).length;
      expect(total).toBe(moveCount);
    }
  });

  test('estimated rating ships a range whenever it ships a value (§8.1)', () => {
    const report = buildFixtureReport();
    for (const colour of ['white', 'black'] as const) {
      const { value, range } = report.players[colour].estimatedRating;
      if (value !== null) expect(range).not.toBeNull();
    }
  });

  test('is deterministic: the same input produces a byte-identical report', () => {
    const first = JSON.stringify(buildFixtureReport());
    const second = JSON.stringify(buildFixtureReport());
    expect(first).toBe(second);
  });

  test('a move that plays the engine\'s best line into a real fork carries tacticOpportunity, found: true', () => {
    // Same fork fixture as classify-tactic-motif.test.ts's FORK_FEN, reached
    // via a [FEN]/[SetUp] PGN header (chess.js honors either) instead of the
    // standard start position.
    const forkPgn = `[White "Alice"]
[Black "Bob"]
[SetUp "1"]
[FEN "4k3/1r6/8/8/2N5/8/8/K7 w - - 0 1"]
[Result "*"]

1. Nd6+ Kd8`;
    const game = parsePgn(forkPgn);
    const evals = buildEvals(game.positions);
    const moves = classifyMoves(game, evals, 'white');
    const report = buildGameReport({
      game,
      evals,
      moves,
      book: buildFixtureBook(),
      engine: { name: 'stockfish', depth: 16, multiPv: 1 },
      priorRating: { white: null, black: null },
      result: { white: 'win', black: 'loss' }
    });

    const forkMove = report.moves.find((move) => move.moveSan === 'Nd6+');
    expect(forkMove?.tacticOpportunity).toEqual({
      type: 'fork',
      found: true,
      detail: 'knight on d6 forks e8 and b7',
      visual: {
        arrows: [
          { from: 'd6', to: 'e8' },
          { from: 'd6', to: 'b7' }
        ],
        highlights: []
      },
      // The verified payoff, which the card's sentence is built from — a
      // claim that can't say what it wins doesn't get one (§3 rule 1).
      gain: { kind: 'material', pawns: 5, prize: 'rook' },
      confidence: 0.85,
      // Multi-label: the knight check also hits the rook with tempo. The
      // card leads with the fork because that is what wins the material.
      motifs: ['fork', 'gainsTempo'],
      // Which move the motif was read off — the engine's own here, since the
      // player played it. Anything replaying the motif (motifToCode's fork
      // piece, pin kind) has to replay this move.
      embodiedBySan: 'Nd6+'
    });
    expect(forkMove?.reasons).toContain('You won a rook through a fork — knight on d6 forks e8 and b7.');
  });

  test('a move that hands over a queen says so, ahead of every other sentence on it', () => {
    // Dany_Abr vs hnpr24, the position before 9...Qd7: the queen steps onto
    // d7 and Bb5 pins it against the king on e8. The card for the move that
    // gave the queen away used to say only what the mover *should* have
    // played; what it cost showed up a ply later, on the opponent's card.
    const blunderPgn = `[White "Dany_Abr"]
[Black "hnpr24"]
[SetUp "1"]
[FEN "r1bqkb1r/pp3ppp/3p1n2/2p3B1/2B1P3/3Q4/PPP2PPP/RN3RK1 b kq - 1 9"]
[Result "1-0"]

9... Qd7 10. Bxf6`;
    const game = parsePgn(blunderPgn);
    const evals: EngineEval[] = [
      { ply: 0, fen: game.positions[0]!.fen, depth: 20, lines: [{ moveUci: 'f8e7', moveSan: 'Be7', cp: 20, mateIn: null }] },
      {
        ply: 1,
        fen: game.positions[1]!.fen,
        depth: 20,
        lines: [
          { moveUci: 'c4b5', moveSan: 'Bb5', cp: 580, mateIn: null, pvSan: ['Bb5', 'Qxb5', 'Qxb5+', 'Nd7', 'Bxf6'] }
        ]
      },
      { ply: 2, fen: game.positions[2]!.fen, depth: 20, lines: [{ moveUci: 'g7f6', moveSan: 'gxf6', cp: 400, mateIn: null }] }
    ];

    const report = buildGameReport({
      game,
      evals,
      moves: classifyMoves(game, evals, 'white'),
      book: buildFixtureBook(),
      engine: { name: 'stockfish', depth: 20, multiPv: 1 },
      priorRating: { white: null, black: null },
      result: { white: 'win', black: 'loss' }
    });

    const blunder = report.moves.find((move) => move.moveSan === 'Qd7');
    expect(blunder?.quality).toBe('blunder');
    expect(blunder?.tacticAllowed).toMatchObject({
      type: 'pin',
      gain: { kind: 'material', prize: 'queen' },
      byMoveSan: 'Bb5'
    });
    // First of the move's tactic sentences, ahead of the "they should have
    // played Be7" one that used to be the whole card, and it names both the
    // prize and the reply that collects it.
    const reasons = blunder?.reasons ?? [];
    const allowedAt = reasons.indexOf(
      'They let you win a queen through a pin two moves away with Bb5 — the queen on d7 is stuck in front of the king.'
    );
    expect(allowedAt).toBeGreaterThanOrEqual(0);
    expect(allowedAt).toBeLessThan(reasons.indexOf('They missed a chance to break the pin with Be7 — the knight on f6 is free to move again.'));
  });

  test('the tactic sentence worth more opens the note, ahead of the prevention sentence already on the move', () => {
    // The prevention sentence is appended by the API's attachTacticPrevention
    // *before* the report is built, so ordering the two is an insertion, not
    // an append — see build-game-report.ts's withTacticSentence.
    const forkPgn = `[White "Alice"]
[Black "Bob"]
[SetUp "1"]
[FEN "4k3/1r6/8/8/2N5/8/8/K7 w - - 0 1"]
[Result "*"]

1. Nd6+ Kd8`;
    const game = parsePgn(forkPgn);
    const evals = buildEvals(game.positions);
    const prevention = {
      type: 'pin',
      prevented: true,
      detail: null,
      visual: null,
      gain: { kind: 'positional', pawns: 0, prize: null }
    } as const;
    const preventionText = tacticPreventionReason({ ...prevention, isUserMove: true });
    const moves = classifyMoves(game, evals, 'white').map((move) =>
      move.moveSan === 'Nd6+'
        ? { ...move, tacticPrevention: prevention, reasons: [...(move.reasons ?? []), preventionText] }
        : move
    );

    const report = buildGameReport({
      game,
      evals,
      moves,
      book: buildFixtureBook(),
      engine: { name: 'stockfish', depth: 16, multiPv: 1 },
      priorRating: { white: null, black: null },
      result: { white: 'win', black: 'loss' }
    });

    const reasons = report.moves.find((move) => move.moveSan === 'Nd6+')?.reasons ?? [];
    const opportunityAt = reasons.indexOf('You won a rook through a fork — knight on d6 forks e8 and b7.');
    expect(opportunityAt).toBeGreaterThanOrEqual(0);
    expect(opportunityAt).toBeLessThan(reasons.indexOf(preventionText));
  });

});
